# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U-QqN3T1w8Pmwn_iqWGywywBfk6dPQhs
"""

import json
import pandas as pd
import plotly.graph_objects as go
 
f = open('/content/data/Stock List.json', "r")
 
data = json.loads(f.read())
 
df = pd.DataFrame(data)
 
fig = go.Figure(data=go.Ohlc(x=df['date'],
                open=df['open'],
                high=df['high'],
                low=df['low'],
                close=df['close']))
 
fig.update_layout(
    title='OHLC CHART',
    yaxis_title='AAPL Stock',
    shapes = [dict(x0='2016-12-09', x1='2016-12-09', y0=0, y1=1, xref='x', yref='paper',line_width=2)],
    annotations=[dict(x='2016-12-09', y=0.05, xref='x', yref='paper',showarrow=False, xanchor='left', text='Increase Period Begins')]
)
 
fig.show()
 
print(df.head())
 
f.close()